// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from './application';

import NestedCommentController from './nested_comment_controller';
application.register('nested-comment', NestedCommentController);